### PR TITLE
Add Chinese

### PR DESCRIPTION
**Pull request by Sunbreak**
Signed-off-by: Sunbreak <sunbreak.wang@gmail.com>

### CODE REVIEW

**Review by bgwastu — APPROVED** [review]
Thank you, @Sunbreak, for the contribution.

**Comment by pavelzw** [comment]
@Sunbreak @bagaswastu 
You still need to add the chinese option in `lib/main.dart`.

**Comment by Sunbreak** [comment]
> @Sunbreak @bagaswastu
> You still need to add the chinese option in `lib/main.dart`.

Didn't know that. `flutter run` stops at splash page. Maybe VPN is needed to access `Library Genesis`

**Comment by bgwastu** [comment]
> > @Sunbreak @bagaswastu
> > You still need to add the chinese option in `lib/main.dart`.
> 
> Didn't know that. `flutter run` stops at splash page. Maybe VPN is needed to access `Library Genesis`

I've already fixed the splash screen issue, it should be work now

**Comment by pavelzw** [comment]
@Sunbreak 
I didn't get Chinese to work on my emulator. Maybe it's because there are multiple Chinese options?
On the [Flutter documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#advanced-locale-definition) there is more info. Maybe you can look into it.

**Comment by Sunbreak** [comment]
> @Sunbreak
> I didn't get Chinese to work on my emulator. Maybe it's because there are multiple Chinese options?
> On the [Flutter documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#advanced-locale-definition) there is more info. Maybe you can look into it.

Checkout https://github.com/bagaswastu/librebook/pull/7

**Pull request merged**
