### PR TITLE
Add localizations

### LINKED ISSUE #1: Translations
Hey there!

How would one contribute translations to this project? I've looked in `/lib` for the `l10n` folder as many Dart apps use it (e.g. https://github.com/manuelvargastapia/libgen_mobile_app/pull/6/files), but I could not find it.

Regards,
Atrate

### PR DESCRIPTION
**Pull request by pavelzw**
This pull request adds a localization structure and localizes the strings into German.
One can localize strings by addings a file in `lang` and adding the language to `lib/app_localizations.dart` and `lib/main.dart`.

Closes #1.

### CODE REVIEW

**Comment by bgwastu** [comment]
Hi, pavelzw, thanks for the contribution 😊

Sorry for this stupid question, If I may know how can this application know the language used by the user? Is the 
application read the language setting from user default language setting? Or the user must set up his own language?

**Comment by pavelzw** [comment]
The application just uses the default settings. If the app is not localized yet, it will use the default language English.

**Comment by pavelzw** [comment]
@bagaswastu 
In this merge, there are now a few not localized strings from your recent commits. You need to change them by replacing [`'Search for book'`](https://github.com/bagaswastu/librebook/blob/9e530df1ddb8ca6df33c323424fd5ece508446ea/lib/ui/views/home/home_view.dart#L111) by `AppLocalizations.of(context).translate('search-book')`. 
Same goes for the strings in `settings_view.dart` and `folder_picker.dart`,

**Comment by pavelzw** [comment]
Also, when you add a new string to `en.json`, you need to add the same string to `de.json` (and all the other languages), because if you don't, the app won't work on these devices.

I also added some todos (for example [here](https://github.com/bagaswastu/librebook/blob/9e530df1ddb8ca6df33c323424fd5ece508446ea/lib/ui/views/search/book_search.dart#L221)) where localizing was not possible without changing the code too much. You need to pass on the `BuildContext` in order to localize the strings.

**Comment by bgwastu** [comment]
I see, I forgot to add that one when resole the merge conflicts, I will add that later on.

I have a question regarding localization, for example, if the language is not yet perfect (still in the process of being translated), can the language be disabled first or switched to English for some parts?

Thanks for your information and help btw!

**Comment by pavelzw** [comment]
I guess you can remove that language in the supported languages in `main.dart` and `app_localizations.dart`. 

Or if you add another string and don't know what the translated string would be, you can just add the English string to the other language files and wait for other people to change the string...

**Comment by pavelzw** [comment]
BTW you should change the link in the README to https://github.com/bagaswastu/librebook/blob/master/lib/main.dart#L32 instead of https://github.com/bagaswastu/librebook/blob/master/lib/main.dart#L31.

**Comment by bgwastu** [comment]
Thank you for reminding,
I'll delete the ```#L31``` instead because the code can still change over time.

**Comment by pavelzw** [comment]
@bagaswastu You just translated to Dutch, the translation needs to be German :D
The two strings need to be `"internal-storage": "Interner Speicher"` and `"download-location-save": "Speicherort"`. 

If you want you can just leave them in English and I can translate them from time to time.

**Comment by bgwastu** [comment]
Ahh, stupid me 🙈 I'll change it to English first asap

**Pull request merged**
